sudo: required
services:
  - docker

before_install:
  - docker build -t idalavye/react-test -f ./client/DockerfileDev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t idalavye/multi-client ./client
  - docker build -t idalavye/multi-nginx ./nginx
  - docker build -t idalavye/multi-worker ./worker
  - docker build -t idalavye/multi-server ./server
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push docker hub
  - docker push idalavye/multi-client
  - docker push idalavye/multi-nginx
  - docker push idalavye/multi-worker
  - docker push idalavye/multi-server
